version: "3"
services:
  php:
    hostname: php-container
    image: devilxatoms/taproject
    ports:
      - "80:80"
    volumes:
      - c:/xampp/htdocs/david:/var/www/html
  node:
    hostname: node-container
    image: node:latest
    ports:
      - "3000:3000"
