version: '2'
services:
  taproject:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: tuadmin
    restart: always
    environment:
      TZ: America/Mexico_City
    ports:
      - 9000:9000
    tty: true
